### PR TITLE
fix: Monero (XMR) errors

### PR DESCRIPTION
**Pull request by mlipovaca**
Hello, sorry for the troubles.

I made a new PR, please test it & make sure it's working before publishing. I copied the same as on fork repository since on christsim/multicoin-address-validator for Monero it exists. I added biginteger file as it was missing and reconfigured files. Hopefully it works, since I can't test it locally, it gives me some errors when trying to run & build package. Let me know if there's any issues, I think from the fork repo, you can check & add what's missing or reconfigure towards to it.

@marksuurland 

Reference: https://github.com/christsim/multicoin-address-validator

### CODE REVIEW

**Comment by marksuurland** [comment]
Thanks for the effort @mlipovaca ! I will merge it and check if its all fine now.

**Comment by marksuurland** [comment]
@mlipovaca Oke did some minor fixes after merging and all tests are green now :) there is however 1 minor thing to fix (I couldn't fix it quickly):

When running npm i:
line 16 of biginteger.js is causing trouble:
`src/crypto/externals/biginteger.js:16:1 - error TS9005: Declaration emit for this file requires using private name 'JSBigInt'. An explicit type annotation may unblock declaration emit.`

If you can have a quick look? Else I will check later.

**Comment by mlipovaca** [comment]
@marksuurland Hey Mark, ty for merging it, I'll check in a little bit, but If I don't do any changes, feel free to check it yourself and solve it. Not gonna guarantee to solve it, if I do, I'll make a new PR then :)

**Comment by marksuurland** [comment]
@mlipovaca Sounds good!

**Comment by mlipovaca** [comment]
> @mlipovaca Sounds good!

Hi @marksuurland I wasn't able to fix the issue / start the build as I'm having issues with PC. If it's all alright besides that, lmk when you release a new version :) . Sorry for the troubles :/

**Comment by marksuurland** [comment]
Hi @mlipovaca no worries, just fixed the issue, and pushed to master, also version 0.5.12 is released including these new currencies, enjoy!
https://www.npmjs.com/package/crypto-address-validator-ts/v/0.5.12

**Pull request merged**
